### ISSUE TITLE
マークダウンよりYAMLの方が記述に向いているのでは？

### ISSUE THREAD

**Issue by beijaflor** [hirokidaichi/uiflow#1]
同じような事ずっと考えていて手を動かせていなかったので、感激しました。

少し触ったりなどしてみたのですが、全体の見通しや構造化とかを考えるとYAMLで以下のように書いた方が自明な部分が増えて良いのではないかな、と感じました。`link`や`screen-image`とか拡張もしやすいですし。
自分で作れよ、、、って話ではあるのですが、まずはフィードバックまで。

``` yaml
-
  id: hoge
  see:
    - hoge
    - uge
  do:
    - fuga
    - muga: hage
-
  id: hage
  see:
    - hoge
    - uge
  do:
    - fuga
    - muga: hoge
```
